### ISSUE TITLE
Metadata reading error

### ISSUE THREAD

**Issue by wldko** [guiwitz/splitmask#3]
Looks to me like a problem in the .nd2 file. 

KeyError                                  Traceback (most recent call last)
/var/folders/2t/tqz_70hd15q6g6898jclrj140000gn/T/ipykernel_88833/4041659791.py in <module>
     22 print(exp_ID)
     23 
---> 24 image = ND2(base_path+image_path)
     25 roi = skimage.io.imread(base_path+roi_path)

~/anaconda3/envs/splitmask/lib/python3.9/site-packages/microfilm/dataset/dataset.py in __init__(self, expdir, channel_name, bad_frames, step, max_time, data_type)
    289         )
    290 
--> 291         self.initialize()
    292 
    293     def initialize(self):

~/anaconda3/envs/splitmask/lib/python3.9/site-packages/microfilm/dataset/dataset.py in initialize(self)
    293     def initialize(self):
    294 
--> 295         self.nd2file = ND2Reader(self.expdir.as_posix())
    296         self.nd2file.metadata["z_levels"] = range(0)
    297 

~/anaconda3/envs/splitmask/lib/python3.9/site-packages/nd2reader/reader.py in __init__(self, fh)
     36         self._fh = fh
     37 
---> 38         self._parser = Parser(self._fh)
     39 
     40         # Setup metadata

~/anaconda3/envs/splitmask/lib/python3.9/site-packages/nd2reader/parser.py in __init__(self, fh)
     34 
     35         # Parse the metadata
---> 36         self._parse_metadata()
     37 
     38     def calculate_image_properties(self, index):

~/anaconda3/envs/splitmask/lib/python3.9/site-packages/nd2reader/parser.py in _parse_metadata(self)
    141         self._label_map = self._build_label_map()
    142         self._raw_metadata = RawMetadata(self._fh, self._label_map)
--> 143         self.metadata = self._raw_metadata.__dict__
    144         self.acquisition_times = self._raw_metadata.acquisition_times
    145 

~/anaconda3/envs/splitmask/lib/python3.9/site-packages/nd2reader/raw_metadata.py in __dict__(self)
     25             dict: the parsed metadata
     26         """
---> 27         return self.get_parsed_metadata()
     28 
     29     def get_parsed_metadata(self):

~/anaconda3/envs/splitmask/lib/python3.9/site-packages/nd2reader/raw_metadata.py in get_parsed_metadata(self)
     55         self._metadata_parsed['num_frames'] = len(self._metadata_parsed['frames'])
     56 
---> 57         self._parse_roi_metadata()
     58         self._parse_experiment_metadata()
     59         self._parse_events()

~/anaconda3/envs/splitmask/lib/python3.9/site-packages/nd2reader/raw_metadata.py in _parse_roi_metadata(self)
    265         for i in range(number_of_rois):
    266             current_roi = raw_roi_data[six.b('m_vectGlobal_%d' % i)]
--> 267             roi_objects.append(self._parse_roi(current_roi))
    268 
    269         self._metadata_parsed['rois'] = roi_objects

~/anaconda3/envs/splitmask/lib/python3.9/site-packages/nd2reader/raw_metadata.py in _parse_roi(self, raw_roi_dict)
    281 
    282         """
--> 283         number_of_timepoints = raw_roi_dict[six.b('m_vectAnimParams_Size')]
    284 
    285         roi_dict = {

KeyError: b'm_vectAnimParams_Size'

**Comment by guiwitz** [comment]
Have you installed the custom version of the nd2reader? If not please do it in the appropriate environment with:
```
pip install git+https://github.com/guiwitz/nd2reader.git@master#egg=nd2reader -U
```

**Comment by wldko** [comment]
Worked, merci.
